name: Lint & Unit test

'on':
  workflow_call:

jobs:
  chefstyle:
    env:
      BUNDLE_WITHOUT: integration
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.1']
    name: Chefstyle on Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1.161.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - uses: r7kamura/rubocop-problem-matchers-action@v1
      - run: bundle exec chefstyle

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Run yaml Lint
        uses: actionshub/yamllint@main

  mdl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v13
        with:
          globs: "**/*.md"

  test:
    name: Unit Test with Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    needs: [mdl, yamllint, chefstyle]
    strategy:
      matrix:
        ruby: ['2.7', '3.0', '3.1']
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1.161.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake test
